services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  # backend:
  #   build: ./backend
  #   container_name: backend
  #   restart: always
  #   depends_on:
  #     - mongodb
  #   environment:
  #     - MONGO_URL=mongodb://mongodb:27017/hackathon
  #   ports:
  #     - "5000:5000"

  # frontend:
  #   build: ./frontend
  #   container_name: frontend
  #   restart: always
  #   ports:
  #     - "3000:3000"

volumes:
  mongodb_data: